In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', 5000)

In [2]:
df = pd.read_csv("../data/combined.csv")
df

,Race,HIV (non-AIDS) Rate,AIDS Rate,HIV/AIDS Rate,Infant Mortality Rate,Insurance Application Rate,"Disease Rate per 100,000",Poverty Rate
0,American Indian and/or Alaska Native,118.6,164.3,282.9,5.35,1.88,133.13,20.2
1,Asian,34.9,48.9,83.8,2.95,3.28,76.71,11.5
2,Black or African American,370.1,595.5,965.7,11.12,5.66,307.39,21.4
3,Hispanic,98.8,164.0,262.8,5.07,4.98,99.63,20.9
4,Mixed Race,79.2,97.0,176.1,10.94,3.09,79.17,13.2
5,White,136.3,208.3,344.5,4.26,3.71,93.82,8.0